# Generated by Django 5.1.4 on 2025-02-02 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projManagement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diminutif", models.CharField(max_length=10, unique=True)),
                ("description", models.CharField(max_length=255)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name="client",
            options={},
        ),
        migrations.RemoveField(
            model_name="client",
            name="actif",
        ),
        migrations.AddField(
            model_name="client",
            name="statut",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mission",
            name="budget",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="mission",
            name="libelle",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="mission",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en cours", "En cours"),
                    ("en attente", "En attente"),
                    ("fermé", "Fermé"),
                ],
                default="En attente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="adresse",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="code_postal",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="date_inscription",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="nom",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="pays",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="prenom",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="telephone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="ville",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="mission",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="missions",
                to="projManagement.client",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mission",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mission",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="mission",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("brouillon", "Brouillon"), ("validé", "Validé")],
                        max_length=20,
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journaux",
                        to="projManagement.mission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_emission", models.DateField(auto_now_add=True)),
                ("montant_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "journal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facture",
                        to="projManagement.journal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ligne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField()),
                ("quantite", models.IntegerField()),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="projManagement.journal",
                    ),
                ),
                (
                    "prestation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="projManagement.prestation",
                    ),
                ),
            ],
        ),
    ]
