# Generated by Django 5.1.4 on 2025-02-02 21:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projManagement",
            "0002_prestation_alter_client_options_remove_client_actif_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="date_creation",
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
