# Generated by Django 5.1.4 on 2025-02-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projManagement", "0003_journal_date_creation"),
    ]

    operations = [
        migrations.AddField(
            model_name="facture",
            name="statut",
            field=models.CharField(
                choices=[
                    ("impayé", "Impayé"),
                    ("payé", "Payé"),
                    ("en retard", "En retard"),
                ],
                default="Impayé",
                max_length=20,
            ),
        ),
    ]
