# Generated by Django 5.1.4 on 2025-02-04 22:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projManagement", "0004_facture_statut"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collaborateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("COMPTABLE", "Comptable"),
                            ("RAF", "Responsable administratif et financier"),
                            ("ASSOCIE", "Associé"),
                        ],
                        max_length=10,
                    ),
                ),
                ("tarif_horaire", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="FeuilleDeTemps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "collaborateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feuilles_de_temps",
                        to="projManagement.collaborateur",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feuilles_de_temps",
                        to="projManagement.mission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LigneDeFeuilleDeTemps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "heures_travaillees",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("description", models.TextField()),
                (
                    "feuille_de_temps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="projManagement.feuilledetemps",
                    ),
                ),
            ],
        ),
    ]
