# Generated by Django 5.1.4 on 2025-02-05 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projManagement", "0005_collaborateur_feuilledetemps_lignedefeuilledetemps"),
    ]

    operations = [
        migrations.AddField(
            model_name="lignedefeuilledetemps",
            name="montant",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="feuilledetemps",
            name="date_creation",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
