# Generated by Django 5.1.4 on 2025-03-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projManagement", "0006_lignedefeuilledetemps_montant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaborateur",
            name="password",
            field=models.CharField(default="test", max_length=128),
            preserve_default=False,
        ),
    ]
