# Generated by Django 5.1.4 on 2025-03-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projManagement", "0007_collaborateur_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="client_logos/"),
        ),
    ]
