# Generated by Django 5.1.4 on 2025-03-26 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projManagement", "0008_client_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_paiement", models.DateField()),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("virement", "Virement bancaire"),
                            ("cheque", "Chèque"),
                            ("especes", "Espèces"),
                            ("cb", "Carte bancaire"),
                        ],
                        default="virement",
                        max_length=20,
                    ),
                ),
                ("commentaire", models.TextField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="projManagement.facture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-date_paiement"],
            },
        ),
    ]
