# Generated by Django 5.1.4 on 2025-03-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projManagement", "0009_paiement"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
