# Generated by Django 5.1.4 on 2025-03-29 01:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projManagement", "0011_alter_collaborateur_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("JOURNAL_VALIDATION", "Validation de journal"),
                            ("CLIENT_CREATION", "Création de client"),
                            ("MISSION_CREATION", "Création de mission"),
                            ("FACTURE_CREATION", "Création de facture"),
                            ("PAIEMENT_CREATION", "Enregistrement de paiement"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("IN_PROGRESS", "En cours"),
                            ("COMPLETED", "Terminé"),
                            ("REJECTED", "Rejeté"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Basse"),
                            ("MEDIUM", "Moyenne"),
                            ("HIGH", "Haute"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to="projManagement.collaborateur",
                    ),
                ),
                (
                    "related_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_tasks",
                        to="projManagement.client",
                    ),
                ),
                (
                    "related_facture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_tasks",
                        to="projManagement.facture",
                    ),
                ),
                (
                    "related_journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_tasks",
                        to="projManagement.journal",
                    ),
                ),
                (
                    "related_mission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_tasks",
                        to="projManagement.mission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("IN_PROGRESS", "En cours"),
                            ("COMPLETED", "Terminé"),
                            ("REJECTED", "Rejeté"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_assignments",
                        to="projManagement.collaborateur",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_tasks",
                        to="projManagement.collaborateur",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="projManagement.taskworkflow",
                    ),
                ),
            ],
        ),
    ]
